version: '3'

services:
  products-db:
    image: postgres
    restart: always
    container_name: products-db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  contacts-db:
    image: postgres
    restart: always
    container_name: contacts-db
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  orders-db:
    image: postgres
    restart: always
    container_name: orders-db
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  gateway-db:
    image: postgres
    restart: always
    container_name: gateway-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
